version: '2'
services:
  api:
    build: .
    ports:
      - "30001:30001"
    depends_on:
      - "mongo"
    links:
      - 'mongo:database'
  mongo:
    image: mongo
    volumes:
      - './docker/mongo:/data/db'
    ports:
      - '27017:27017'
